vcom -work grlib $GRLIB/lib/grlib/stdlib/version.vhd
vcom -work grlib $GRLIB/lib/grlib/stdlib/config_types.vhd
vcom -work grlib $GRLIB/lib/grlib/stdlib/config.vhd
vcom -work grlib $GRLIB/lib/grlib/stdlib/stdlib.vhd
vcom -work grlib $GRLIB/lib/grlib/stdlib/stdio.vhd
vcom -work grlib $GRLIB/lib/grlib/stdlib/testlib.vhd
vcom -work grlib $GRLIB/lib/grlib/amba/amba.vhd
vcom -work grlib $GRLIB/lib/grlib/amba/devices.vhd
vcom -work grlib $GRLIB/lib/grlib/amba/defmst.vhd
vcom -work techmap $GRLIB/lib/techmap/gencomp/gencomp.vhd
vcom -work techmap $GRLIB/lib/techmap/inferred/memory_inferred.vhd
vcom -work techmap $GRLIB/lib/techmap/maps/allmem.vhd
vcom -work techmap $GRLIB/lib/techmap/maps/syncram.vhd
vcom -work gaisler $GRLIB/lib/gaisler/misc/misc.vhd
